LLM Integration
uhh-lt/dats pull request #412
Opened 2024-08-26 14:44 UTC by bigabig

- add ollama to docker-compose
- add ollama client as new dependency for backend / celery worker (we need to rebuild containers)
- adds new redis channel for llm tasks
- adds endpoints for llm tasks
- new feature: llm assistant for doc tagging

2024-08-26 14:50 UTC, bigabig commented
Todos:
- [ ] LLM Annotation in LLM Assistant
- [ ] LLM Metadata Extraction in LLM Assistant
- [ ] LLM Paraphrasing / Summarization as new option when annotating
- [ ] LLM Jobs Manager (Similar to the Pre-pro jobs / Background Jobs UI
- [ ] Delete finished LLM Jobs
- [ ] (maybe?) Introduce device id env variable

2024-08-27 07:59 UTC, floschne requested changes
Please add `OllamaService` and `LLMService` initializations to the `startup.py::init_services` method :)

2024-08-27 07:59 UTC, floschne commented on docker/docker-compose.yml
> +    networks:
I would add a docker profile "ollama" similar to the "ray" profile to control whether the container should be started or not

2024-08-27 07:59 UTC, floschne commented on backend/src/app/core/data/llm/llm_service.py
> +        # check that the answer starts with "Kategorie:"
Is German on purpose here?

2024-09-25 08:20 UTC, merged